version: '2'

services:
  elasticsearch-master:
    build: search_engine/elasticsearch
    image: gurufinder/elasticsearch
    restart: always
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - gurufinder
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: "${ELASTIC_MEM_LIMIT}"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./data/master:/usr/share/elasticsearch/data
    container_name: gurufinder_elasticsearch-master

  elasticsearch-node:
    build: search_engine/elasticsearch
    image: gurufinder/elasticsearch
    restart: always
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - gurufinder
    depends_on:
      - elasticsearch-master
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: "${ELASTIC_MEM_LIMIT}"
    cap_add:
      - IPC_LOCK
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./data/node:/usr/share/elasticsearch/data
    command: elasticsearch -E discovery.zen.ping.unicast.hosts=elasticsearch-master -E network.host=0.0.0.0 -E discovery.zen.minimum_master_nodes=1
    container_name: gurufinder_elasticsearch-node

  logstash:
    build: twitter_crawlers/logstash_crawler
    image: gurufinder/logstash
    command: -f /etc/logstash/conf/
    restart: always
    volumes:
      - ./twitter_crawlers/logstash_crawler/config:/etc/logstash/conf
    networks:
      - gurufinder
    depends_on:
      - elasticsearch-node
    container_name: gurufinder_logstash
    mem_limit: "${ELASTIC_MEM_LIMIT}"
    environment:
      - TWITTER_CONSUMER_KEY
      - TWITTER_CONSUMER_SECRET
      - TWITTER_OAUTH_SECRET
      - TWITTER_OAUTH_TOKEN

  beats:
    build: search_engine/beats
    image: gurufinder/beats
    restart: always
    volumes:
      - ./search_engine/beats/config:/usbr/share/filebeat
      - ./data/logs:/usr/share/filebeat/data/logs
    networks:
      - gurufinder
    depends_on:
      - elasticsearch-node
    container_name: gurufinder_beats
    command: filebeat -e -c /usbr/share/filebeat/filebeat.yml

  kibana:
    build: search_engine/kibana
    image: gurufinder/kibana
    restart: always
    ports:
      - "80:5601"
    networks:
      - gurufinder
    depends_on:
      - elasticsearch-node
    container_name: gurufinder_kibana
    command: kibana -e http://elasticsearch-node:9200

  tweepy_crawler:
    build: .
    image: gurufinder/tweepy_crawler
    restart: on-failure
    networks:
      - gurufinder
    depends_on:
      - elasticsearch-node
    container_name: gurufinder_tweepy_crawler
    environment:
      - TWITTER_USER
      - TWITTER_CONSUMER_KEY
      - TWITTER_CONSUMER_SECRET
      - TWITTER_OAUTH_SECRET
      - TWITTER_OAUTH_TOKEN
    volumes:
      - ./data/logs:/gurufinder/logs
    working_dir: /gurufinder
    command: python twitter_crawlers/tweepy_crawler/tweepy_crawler.py -u $TWITTER_USER

  fit_gururecommender:
    build: .
    image: gurufinder/gururecommender
    networks:
      - gurufinder
    depends_on:
      - elasticsearch-node
    container_name: gurufinder_fit_gururecommender
    volumes:
      - ./data/logs:/gurufinder/logs
      - ./data/models:/gurufinder/gururecommender/models
    working_dir: /gurufinder
    mem_limit: 200G
    cpuset: 0-45
    command: python gururecommender/guru_recommender.py -a fit -m lda

  predict_gururecommender:
    build: .
    image: gurufinder/gururecommender
    restart: on-failure
    networks:
      - gurufinder
    depends_on:
      - elasticsearch-node
    container_name: gurufinder_predict_gururecommender
    volumes:
      - ./data/logs:/gurufinder/logs
      - ./data/models:/gurufinder/gururecommender/models
    working_dir: /gurufinder
    command: python gururecommender/guru_recommender.py -a predict -m lda

volumes:
  data:
    driver: local
    driver_opts:
      device: ./data/

networks:
  gurufinder:
    driver: bridge
