filebeat.prospectors:
  - paths:
      - /usr/share/filebeat/data/logs/tweets*
    input_type: log
    tags: ["gurus"]

  - paths:
      - /usr/share/filebeat/data/logs/predict.log
    input_type: log
    tags: ["predictions"]

output.logstash:
  hosts: ["logstash:5044"]